// Generated by CoffeeScript 1.7.1
(function() {
  var parse, parseWatch, _ref;

  _ref = require('../index'), parse = _ref.parse, parseWatch = _ref.parseWatch;

  parse(function() {
    this.collect("client", function() {
      return [
        this.dest("_site/assets/css/client.css", function() {
          return this.concatcss(function() {
            return this.less("**/*.less");
          });
        }), this.toDir("_site/images", function() {
          return this.glob('assets/**/*.png');
        }), this.dest("_site/assets/js/client.js", function() {
          return this.concatjs(function() {
            return this.livescript("src/assets/**/*.ls");
          });
        })
      ];
    });
    return this.collect("server", function() {
      return this.toDir("server/js", function() {
        return this.livescript("src/server/**/*.ls");
      });
    });
  });

}).call(this);
